parinTNK/course_flow

src/app/page.tsx
src/components/nav.tsx

This pull request refactors the `NavBar` component to dynamically fetch user data from Supabase, removes mock user data from the `Home` page, and applies consistent formatting improvements across files. Below are the key changes grouped by theme:
* Updated `NavBar` to fetch user data dynamically using Supabase's authentication and profile tables. This replaces the previous approach of passing a `user` prop, and introduces a `useEffect` hook to handle the data fetching. [[1]](diffhunk://#diff-65361c28a5fdb7491cc156b37962d449f0d58ee1c9ca2176f9789b0db1e44f2bL3-R17) [[2]](diffhunk://#diff-65361c28a5fdb7491cc156b37962d449f0d58ee1c9ca2176f9789b0db1e44f2bR27-R62)
* Removed mock user data (`mockUser`) from the `Home` page and updated the `NavBar` usage to no longer require a `user` prop.
* …

feat(nav): implement user fetching and profile display in NavBar

---

package-lock.json
package.json
src/app/(auth)/login/page.tsx
src/app/(auth)/login/types.ts
src/app/(auth)/login/utils/auth.ts
src/app/admin/components/CourseRow.tsx
src/app/admin/components/CoursesTable.tsx
src/app/admin/components/Sidebar.tsx
src/app/admin/context/CoursesContext.tsx
src/app/admin/dashboard/page.tsx
src/app/admin/layout.tsx
src/app/admin/login/page.tsx
src/app/admin/login/type.ts
src/app/admin/login/utils/action.ts
src/app/admin/login/utils/validations.ts
src/hooks/withAuth.tsx
src/lib/supabaseClient.ts
src/lib/withAdminAuth.tsx
src/middleware.ts

This pull request introduces significant updates to the authentication flow, improves code readability and consistency, and includes minor dependency updates. The most notable changes involve replacing the existing login logic with Supabase-based authentication, adding new utility functions, and refactoring components for better formatting and maintainability.
* Replaced the `login` function with a new `signInWithEmail` function that integrates Supabase's `auth.signInWithPassword` for handling user authentication. This includes error handling for invalid credentials and unconfirmed emails. (`src/app/(auth)/login/page.tsx`, `src/app/(auth)/login/utils/auth.ts`) [[1]](diffhunk://#diff-684ca781af5e9dd83b8953f951396e659303a92c260ea70ea4b823946aa57875L2-R8) …

fix: move auth to client-side & add middleware for session protection

---

src/app/(main)/course-detail/[courseId]/page.tsx
src/app/(main)/my-courses/page.tsx
src/app/api/users/[userId]/courses/route.ts
src/components/CourseCard.tsx

This PR implements the course-detail page with full support for both guest and authenticated users.
It includes course details, module listing, subscription actions, and related courses.
**Features included:**
Dynamic course fetching by courseId from Supabase
Guest access to course details and modules
Subscription status check for logged-in users
Add to Wishlist / Subscribe buttons with conditional login redirect (planned)
Loading states with LoadingSpinner and layout consistency
Sticky sidebar for key course actions
Carousel of other related courses
**Improvements:**
Separated fetching course content from subscription check (for performance)
Added fallback layout and min-height during loading to prevent footer jump
Used query params (?redirect=...) to support future login redirect flow …

feat(course-detail): implement course detail page with modules, subscription check, and guest support

---

src/app/(main)/payment/[courseId]/order-completed/page.tsx
src/app/(main)/payment/[courseId]/page.tsx

replace mock user with user auth

refactor: replace mock user with user auth

---

src/app/admin/components/PromoCodeSection.tsx
src/app/admin/components/Sidebar.tsx
src/app/admin/dashboard/create-courses/page.tsx
src/app/admin/dashboard/page.tsx
src/app/admin/layout.tsx
src/app/api/admin/courses-create/route.ts
src/app/api/courses-list/route.ts
src/components/ui/ButtonT.tsx

This pull request introduces a new "Create Course" feature in the admin dashboard, along with UI enhancements, form validation, and backend updates. The changes include the addition of a `PromoCodeSection` component, updates to the course creation flow, and improvements to existing components and APIs.
* Added `PromoCodeSection` component for managing promo codes, including fields for promo code selection, minimum purchase amount, and discount type (`src/app/admin/components/PromoCodeSection.tsx`).
* Implemented a new `CreateCourse` page with form validation, API integration for course creation, and support for promo code data (`src/app/admin/dashboard/create-courses/page.tsx`).
* Updated the `Sidebar` component to include a fixed layout for better navigation (`src/app/admin/layout.tsx`). …

feat: implement course creation page with validation

---

src/app/(main)/course-detail/[courseId]/page.tsx

This PR introduces subscription and wishlist functionality for individual courses in the Course Detail page. And then cleans up the `CourseDetailPage` component by removing unnecessary code and improving overall readability and state management, while preserving all intended functionality related to wishlist, subscription, and learning access.
---
##Course Detail Page:
- Fetch course, lesson, and other related courses using Supabase.
- Handle subscription status from Supabase subscriptions table.
- “Add to Wishlist” and “Remove from Wishlist” toggle behavior.
- Confirmation modal shown before adding or removing.
- Toast notifications shown after action.
- Disabled when already subscribed.
- Requires user to be logged in (redirects to /login?redirect=...).
- Shows a confirmation modal …

merge user/course detail page to dev feat: Implement Subscribe & Wishlist Features on Course Detail Page

---

src/app/api/admin/courses-create/route.ts
src/app/api/admin/courses-update/[id]/route.ts
src/app/api/payment/charge/route.ts
src/components/learning/SubLessonVideoPlayer.tsx
src/lib/bangkokTime.ts

This pull request introduces a utility function, `getBangkokISOString`, to standardize timestamps in Bangkok time across multiple modules. The changes ensure consistency in date and time handling by replacing `new Date().toISOString()` with this new utility function in various parts of the application.
* [`src/lib/bangkokTime.ts`](diffhunk://#diff-829206073b7697ba8cb51cbdd2ab8a35310be31e6727bcff840cb0463131924dR1-R6): Added a new utility function, `getBangkokISOString`, to generate ISO 8601 formatted timestamps in Bangkok time.
* [`src/app/api/admin/courses-create/route.ts`](diffhunk://#diff-a8406ae0303413430984603c82eca6616248e4a54141bdcefef8b3e9771bbbdbR4): Updated the `POST` method to use `getBangkokISOString` for `created_at` and `updated_at` fields when inserting a new course. …

fix: time zone when create and update

---

src/app/(main)/our-courses/page.tsx
src/app/(main)/profile/page.tsx
src/components/footer.tsx
src/components/nav.tsx

**This PR addresses the following updates:**
**Navbar**
Replaced window.location.href with Next.js router navigation (router.push) to prevent full page reloads when clicking on the nav dropdown items (e.g., Profile, My Courses).
This improves performance and ensures the NavBar doesn't unnecessarily refetch the user on every navigation.
**Footer**
minor adjust on link path
**Our Courses Page**
fix type issue

fix(navbar, footer, our-courses): prevent full reload on nav item click and fix minor layout issues

---

src/app/(auth)/login/page.tsx
src/components/nav.tsx
src/lib/supabaseClient.ts
src/middleware.ts

This pull request introduces several updates to enhance session management, user authentication, and navigation behavior across the application. The changes include improvements to session handling during login and logout, the addition of middleware for route protection, and updates to the Supabase client configuration.
* **Login Page Enhancements**:
- Added a session check on page load to redirect authenticated users to a specified `redirectUrl` or the homepage. Includes a loading spinner while checking the session. (`src/app/(auth)/login/page.tsx`, [src/app/(auth)/login/page.tsxL4-R49](diffhunk://#diff-684ca781af5e9dd83b8953f951396e659303a92c260ea70ea4b823946aa57875L4-R49))
- Refactored localStorage updates during login to use a more concise approach for storing user data. …

feat: implement authentication middleware and improve navigation flow

---

package-lock.json
package.json
src/app/(main)/course-learning/[courseId]/learning/page.tsx
src/components/learning/Assignment.tsx
src/components/learning/Sidebar.tsx
src/components/learning/SubLessonVideoPlayer.tsx
src/components/learning/context/LearningContext.tsx
src/components/learning/context/ProgressContext.tsx
src/components/ui/ButtonT.tsx

This PR finalizes the mobile/desktop UX for the learning flow and ensures seamless interaction across sub-lessons. And improves the assignment submission experience with better timestamp accuracy and reset behavior.
- Implement responsive design for the learning page on both mobile and desktop (Sidebar, Video, Assignment).
- Replace lesson sidebar with Radix UI Accordion for better toggle UX.
- Auto-scroll to video section when selecting sub-lessons from sidebar or using Prev/Next buttons.
- Ensure Prev/Next buttons are disabled when at the first or last sub-lesson.
- Use `ButtonT` component for `Next Lesson` and `Send Assignment` buttons.
- Adjust button alignment and section spacing based on Figma spec (mobile/desktop).
- Improve disabled button appearance (opacity + cursor).
- Refactor …

merge user/course learning page to dev enhance responsive layout and improve lesson navigation UX

---

src/app/(main)/my-courses/page.tsx

edit style to fix profile image display as circular

fix(ui): profile image display as circular

---

src/app/(main)/profile/page.tsx
src/app/(main)/profile/utils/validation.ts

This pull request introduces several updates to the `ProfilePage` component and its related utilities to enhance functionality, improve validation, and refine the user interface. Key changes include renaming the `firstName` field to `name`, adding validation for profile updates and email confirmation, and improving the layout and styling of the profile page.
* Replaced `firstName` with `name` across the `ProfilePage` component and validation logic to standardize naming conventions. This includes updates to the `FormData` interface, state initialization, and payload generation for profile updates. [[1]](diffhunk://#diff-cbba2d543f4f8d47af37c1212c7c38eadde55af807b7ad8717fc2644167cc566L27-R26) [[2]](diffhunk://#diff-cbba2d543f4f8d47af37c1212c7c38eadde55af807b7ad8717fc2644167cc566L41-R40) …

feat(profile): improve form validation and align UI with Figma design

---

src/app/(main)/our-courses/page.tsx

This pull request makes minor adjustments to the padding of elements on the "Our Courses" page to improve visual spacing and layout consistency.

style: adjust padding in CoursesPage layout for improved spacing

---

package-lock.json
package.json
src/app/(main)/course-detail/[courseId]/page.tsx
src/components/CourseCard.tsx
src/components/course/CourseAttachment.tsx
src/components/course/CourseDetailSection.tsx
src/components/course/CourseModules.tsx
src/components/course/CourseSidebar.tsx
src/components/course/CourseTrailerVideo.tsx
src/components/course/OtherCoursesCarosel.tsx
src/components/course/modals/SubscribeModal.tsx
src/components/course/modals/WishlistModal.tsx
src/hooks/useCourseData.ts
src/hooks/useSubscription.ts
src/hooks/useWishlist.ts
src/types/Course.ts

**Refractor course:**
**What’s changed**
- Refactored CourseDetailPage to use custom hooks:
> - useCourseData for fetching course, modules, and other courses
> - useSubscription for checking subscription status
> - useWishlist for wishlist toggle state
- Replaced CourseWithTotalLesson with lightweight CourseSummary type for CourseCard
- Updated CourseCard to use only essential fields (name, summary, cover_image_url, lessons.length, total_learning_time)
- Removed unused logic and fields related to sub_lessons.count
- Added fallback for !course (course not found)
- Cleaned up unused imports and states
**Why**
- Improve readability and maintainability
- Prevent overfetching unnecessary fields from Supabase
- Align types strictly with usage (type-safe, easier autocomplete)
- Make components …

Refactor: Extract course detail logic to custom hooks and remove unused types & Feat: implement wishlist feature

---

src/app/admin/components/PromoCodesTable.tsx
src/app/admin/components/PromoRow.tsx
src/app/admin/components/Sidebar.tsx
src/app/admin/dashboard/Promo code/page.tsx
src/app/admin/dashboard/promo-codes/page.tsx
src/app/api/promocodes/route.ts

This pull request introduces a new feature for managing promo codes in the admin dashboard. It includes a complete implementation of the promo codes table, row components, and the corresponding backend API route. Additionally, it updates the navigation path and removes an unused page. Below are the most important changes grouped by theme:
* Added `PromoCodesTable` component to display a table of promo codes, including fields such as promo code, discount type, and courses included. It also handles empty states. (`src/app/admin/components/PromoCodesTable.tsx`)
* Added `PromoRow` component for rendering individual rows in the promo codes table, including edit and delete buttons with placeholder functionality. (`src/app/admin/components/PromoRow.tsx`)
* Implemented a new page `PromoCodesPage` …

feat: create admin promo code list UI and fetch data from API

---

src/app/(main)/wishlist/page.tsx
src/app/api/wishlist/route.ts

This pull request introduces a new "Wishlist" page for the application, including both frontend and backend implementations. Key changes include building a dynamic, paginated wishlist UI and creating an API endpoint to fetch wishlist data from the database.
* Replaced the placeholder `page` component in `src/app/(main)/wishlist/page.tsx` with a fully functional `WishlistPage` component. This includes state management for wishlist items, loading states, error handling, and pagination. It also integrates components like `CourseCard`, `Pagination`, and `LoadingSpinner` to display wishlist data dynamically.
* Added a new API route in `src/app/api/wishlist/route.ts` to fetch wishlist data from the database. This includes support for pagination, fetching associated course and lesson details, …

feat: add wishlist functionality with API integration and UI updates

---

src/middleware.ts

This pull request refactors the `middleware` function in `src/middleware.ts` to improve modularity and readability, while also enhancing the handling of authentication and path-specific logic. The changes introduce helper functions to categorize paths and separate logic for admin and user authentication.
* Introduced helper functions (`isStaticResource`, `isPublicPath`, `isProtectedPath`, `isAdminPath`) to categorize paths, replacing hardcoded path checks with reusable logic.
* Refactored admin authentication logic into a dedicated `handleAdminAuth` function, improving clarity and reusability. Added constants for cookie names and expiry times to reduce duplication.
* Extracted user authentication logic into a separate `handleUserAuth` function, simplifying the main `middleware` function …

refactor(auth): improve authentication middleware and cookie management

---

src/app/(main)/course-learning/[courseId]/learning/CourseContent.tsx
src/app/(main)/payment/[courseId]/order-completed/page.tsx
src/app/api/payment/charge/route.ts
src/app/context/draftContext.tsx

feat(wishlist, course, draft): update wishlist after payment, sync subscription date, and improve draft handling
- Removes course from wishlist after successful payment
- Sets course subscription date based on payment date (getBangkokISOString) for consistency
- Allows setDirty to accept an answer parameter in draft module

feat(wishlist, course, draft): update wishlist and fix course, draft

---

src/components/learning/SubLessonVideoPlayer.tsx

This pull request introduces several enhancements to the `LessonVideoPlayer` component in `src/components/learning/SubLessonVideoPlayer.tsx`, focusing on improving user experience, progress tracking, and lesson completion handling. The most significant changes include adding a completion modal, refining progress tracking logic, and improving the user interface for resuming videos.
* Added a modal (`ConfirmationModal`) that appears when a lesson ends, allowing users to confirm their understanding or rewatch the lesson. Includes logic to determine whether the modal should be shown based on watch time and progress. [[1]](diffhunk://#diff-89b8640ae95cb01d652f5e04fbbe92f2a126ed51c328524bf062fd49b8f31c9eL135-R196) [[2]](diffhunk://#diff-89b8640ae95cb01d652f5e04fbbe92f2a126ed51c328524bf062fd49b8f …

feat: user skip video

---

src/components/learning/Assignment.tsx

This PR addresses two issues in the assignment component:
1. Character Limit Enforcement
- Ensures that users cannot input more than 500 characters using maxLength={500}.
- Prevents submission of answers exceeding 500 characters.
2. UI Overflow Fix for Submitted Answers
- Adds whitespace-pre-wrap and break-words to the answer preview section.
- Ensures long or unbroken content wraps properly within the container.
These changes preserve the original autosave and submission logic while improving input validation and display formatting.

User/course learning page: Fix assignment answer input limit and display overflow issue

---

next.config.ts
src/app/admin/components/CourseFormView.tsx
src/app/admin/components/FileUpload.tsx
src/app/admin/dashboard/create-courses/page.tsx
src/app/admin/dashboard/edit-courses/[courseId]/page.tsx
src/app/admin/hooks/useCourseForm.ts
src/app/api/upload-pdf/route.ts

This pull request introduces a new file upload feature for course attachments, focusing on PDF files. It includes backend support for file uploads, frontend components for handling file selection and upload, and updates to the course form logic to manage attachment data. The most important changes are grouped into backend functionality, frontend implementation, and integration updates.
* Added a new API route `src/app/api/upload-pdf/route.ts` to handle PDF file uploads, including validation for file type and size, and integration with Supabase storage for saving and retrieving public URLs.
* Created a new `FileUpload` component in `src/app/admin/components/FileUpload.tsx` to manage file selection, drag-and-drop functionality, upload progress, and error handling. It supports file removal …

feat: Attach File upload

---

src/app/admin/components/AssignmentFormView.tsx
src/app/admin/components/AssignmentsRow.tsx
src/app/admin/components/ComboboxSelect.tsx
src/app/admin/components/ConfirmationModal.tsx
src/app/admin/components/CourseRow.tsx
src/app/admin/hooks/useAssignmentForm.ts

This PR includes a comprehensive set of UI/UX improvements across the admin dashboard, including the assignment form, confirmation modals, and the course list table.
- Replaced native `<select>` with searchable dropdowns (Course, Lesson, Sub-lesson) using Command component from shadcn/ui.
- Alphabetically sorted dropdown options for better UX.
- Substring search support (e.g., searching "js" will match "Node.js").
- Sticky search bar with `max-h-[250px]` and scrollable options.
- Full keyboard navigation support (↑ ↓ Enter) within dropdowns.
- Aligned dropdown widths visually for consistent form layout.
- Field-level validation errors now auto-clear on input or selection change.
- Added `cursor-pointer` to Confirm and Cancel buttons to improve affordance.
- This update applies globally to …

Enhance Assignment Form UX, Searchable Dropdowns, and Course List Tooltip Improvements
